/** @type {import('next').NextConfig} */

const {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  VERCEL_URL,
  VERCEL_ENV,
  WORKER_SERVER,
} = process.env;

const nextConfig = {
  reactStrictMode: true,
  env: {
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    VERCEL_URL,
    VERCEL_ENV,
    WORKER_SERVER,
  },
};

module.exports = nextConfig;
